(() => {
  const PACKS = [
    ['Beats from the Streets','1 Beats from the Streets','P1'],['Hello My Name Is','2 Hello My Name Is','P2'],['Run for the Rainbow','3 Run for the Rainbow','P3'],['Daddy Drove a Pickup','4 Daddy Drove a Pickup','P4'],['Stretch before Sweat','5 Stretch before Sweat','P5']
  ];
  const LANE_INFO = { beat:['Beat','Back Beats'],riff:['Riff','Riffs'],lick:['Lick','Licks'],run:['Run','Runs'] };
  const $ = s => document.querySelector(s); const status = msg => $('#status').textContent = msg;
  const pack = $('#pack'); PACKS.forEach(([name]) => pack.add(new Option(name,name)));
  let ctx, master, destination, bpm = 100, active = {}, linked = new Set(), recordingSlot = 'A', recordingBuffers = {A:null,B:null}, recordingSources = {}, songRecorder, songChunks = [], songUrl, songTimer, songSeconds = 0, isSongPlaying = false, inputRecorder, inputChunks = [], inputStopTimer;
  const laneNodes = {}, fx = {input: null, output: null, lfo:null, delay:null, filter:null, shaper:null};
  function initAudio(){
    if(ctx) return; ctx = new AudioContext(); master = ctx.createGain(); master.gain.value = .82; destination = ctx.createMediaStreamDestination(); master.connect(ctx.destination); master.connect(destination);
    for(const lane of Object.keys(LANE_INFO)){ const input=ctx.createGain(), output=ctx.createGain(); input.connect(output).connect(master); laneNodes[lane]={input,output}; }
    fx.input=ctx.createGain(); fx.output=ctx.createGain(); fx.delay=ctx.createDelay(2); fx.filter=ctx.createBiquadFilter(); fx.filter.type='lowpass'; fx.shaper=ctx.createWaveShaper(); fx.lfo=ctx.createOscillator(); const lfoGain=ctx.createGain(); fx.lfo.connect(lfoGain); lfoGain.connect(fx.output.gain); fx.lfo.start(); fx.input.connect(fx.delay).connect(fx.filter).connect(fx.shaper).connect(fx.output).connect(master); updateFX();
  }
  const fileFor = (lane,index) => { const [,,prefix] = PACKS.find(x=>x[0]===pack.value); const folder = PACKS.find(x=>x[0]===pack.value)[1]; return `audio/${encodeURIComponent(folder)}/${prefix}_B${({beat:1,riff:2,lick:3,run:4}[lane])}_${LANE_INFO[lane][0]}_0${index}.wav`; };
  const recordingFile = index => { const [,,prefix] = PACKS.find(x=>x[0]===pack.value); const folder = PACKS.find(x=>x[0]===pack.value)[1]; return `audio/${encodeURIComponent(folder)}/${prefix}_B5_Rec_0${index}.wav`; };
  function loadPackRecordings(){ recordingBuffers={A:recordingFile(1),B:recordingFile(2)}; $('#inputPlay').disabled=false;$('#inputLoop').disabled=false; }
  function addPads(){ for(const lane of Object.keys(LANE_INFO)){ const holder=$('#'+lane+'Pads'); holder.innerHTML=''; for(let i=1;i<=3;i++){const b=document.createElement('button');b.className='pad';b.dataset.lane=lane;b.dataset.index=i;b.setAttribute('aria-pressed','false');b.textContent=`${LANE_INFO[lane][1]} ${i}`;b.setAttribute('aria-label',`${LANE_INFO[lane][1]} loop ${i}, stopped`);b.onclick=()=>toggleLoop(lane,i,b);holder.append(b);} } }
  async function toggleLoop(lane,index,button){ initAudio(); await ctx.resume(); if(isSongPlaying) return; if(active[lane]?.index===index){ stopLane(lane); status(`${LANE_INFO[lane][1]} muted.`); return; } stopLane(lane); const audio=new Audio(fileFor(lane,index)); audio.loop=true; audio.playbackRate=bpm/100; const source=ctx.createMediaElementSource(audio); source.connect(linked.has(lane)?fx.input:laneNodes[lane].input); audio.play(); active[lane]={audio,source,index}; document.querySelectorAll(`[data-lane="${lane}"].pad`).forEach(b=>{const on=+b.dataset.index===index;b.classList.toggle('active',on);b.setAttribute('aria-pressed',String(on));b.setAttribute('aria-label',`${LANE_INFO[lane][1]} loop ${b.dataset.index}, ${on?'playing':'stopped'}`)}); status(`${LANE_INFO[lane][1]} ${index} playing.`); }
  function stopLane(lane){ if(!active[lane])return; active[lane].audio.pause(); active[lane].source.disconnect(); delete active[lane]; document.querySelectorAll(`[data-lane="${lane}"].pad`).forEach(b=>{b.classList.remove('active');b.setAttribute('aria-pressed','false');b.setAttribute('aria-label',`${LANE_INFO[lane][1]} loop ${b.dataset.index}, stopped`)}); }
  function wireLinks(){ document.querySelectorAll('.link').forEach(btn=>btn.onclick=()=>{const lane=btn.dataset.lane; linked.has(lane)?linked.delete(lane):linked.add(lane);btn.setAttribute('aria-pressed',String(linked.has(lane))); if(active[lane]){const a=active[lane];a.source.disconnect();a.source.connect(linked.has(lane)?fx.input:laneNodes[lane].input);} status(`${LANE_INFO[lane][1]} ${linked.has(lane)?'linked to':'unlinked from'} effects.`);}); }
  function updateFX(){ if(!ctx)return; const type=$('#effect').value,x=+$('#fxX').value/100,y=+$('#fxY').value/100; fx.filter.frequency.value=300+Math.pow(1-y,2)*12000; fx.filter.Q.value=x*18; fx.shaper.curve=type==='distortion'?makeCurve(20+x*500):null; fx.lfo.frequency.value=type==='tremolo'?1+x*12:type==='flanger'?0.1+x*4:type==='phaser'?1+x*8:0.01; fx.output.gain.value=type==='tremolo'?.55+y*.4:1; fx.delay.delayTime.value=(type==='echo'||type==='flanger'||type==='phaser')?.02+x*.7:0; Object.values(active).forEach(({audio})=>{if(type==='rewind')audio.playbackRate=.5+x*1.5; else if(type==='fr') audio.playbackRate=.35+x*1.5; else audio.playbackRate=bpm/100;}); }
  function makeCurve(amount){ const curve=new Float32Array(44100); for(let i=0;i<curve.length;i++){const x=i*2/curve.length-1;curve[i]=(1+amount)*x/(1+amount*Math.abs(x));} return curve; }
  function setBPM(value){ bpm=Math.max(60,Math.min(180,value)); $('#bpmOut').textContent=`${bpm} BPM`; Object.values(active).forEach(({audio})=>audio.playbackRate=bpm/100); updateFX(); }
  function click(){ if(!ctx)return; const o=ctx.createOscillator(),g=ctx.createGain();o.frequency.value=1500;g.gain.setValueAtTime(.12,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.05);o.connect(g).connect(master);o.start();o.stop(ctx.currentTime+.06); }
  function recordSong(){ initAudio(); if(songRecorder?.state==='recording'){ songRecorder.stop(); return; } songChunks=[]; songSeconds=0; $('#songRecord').disabled=true; status('Four-beat count-in. Song recording will start after four clicks.'); let n=0; const count=setInterval(()=>{click(); n++; if(n===4){clearInterval(count); songRecorder=new MediaRecorder(destination.stream); songRecorder.ondataavailable=e=>songChunks.push(e.data); songRecorder.onstop=finishSong; songRecorder.start(); $('#songRecord').disabled=false;$('#songRecord').setAttribute('aria-pressed','true');status('Recording song. No time limit.'); songTimer=setInterval(()=>{$('#songTime').textContent=new Date(++songSeconds*1000).toISOString().slice(14,19)},1000);}},600); }
  function finishSong(){ clearInterval(songTimer); if(songUrl)URL.revokeObjectURL(songUrl);songUrl=URL.createObjectURL(new Blob(songChunks,{type:songChunks[0]?.type||'audio/webm'}));$('#songRecord').setAttribute('aria-pressed','false');$('#songPlay').disabled=false;$('#exportSong').disabled=false;status(`Song captured: ${$('#songTime').textContent}.`); }
  function toggleSongPlayback(){if(!songUrl)return; const audio=$('#songPreview')||Object.assign(document.createElement('audio'),{id:'songPreview'}); if(!audio.parentNode)document.body.append(audio); if(isSongPlaying){audio.pause();isSongPlaying=false;$('#songPlay').textContent='▶ Play Song';enableControls(true);return;} audio.src=songUrl;audio.onended=()=>{isSongPlaying=false;$('#songPlay').textContent='▶ Play Song';enableControls(true);};isSongPlaying=true;audio.play();$('#songPlay').textContent='■ Stop Song';enableControls(false);}
  function enableControls(enabled){document.querySelectorAll('.lanes button,.lower button,.lower select,.lower input,#pack,#reset').forEach(x=>x.disabled=!enabled);$('#songPlay').disabled=!songUrl;}
  async function recordInput(){initAudio();if(inputRecorder?.state==='recording'){inputRecorder.stop();return;} try{const stream=await navigator.mediaDevices.getUserMedia({audio:true}); inputChunks=[];inputRecorder=new MediaRecorder(stream);inputRecorder.ondataavailable=e=>inputChunks.push(e.data);inputRecorder.onstop=()=>{const blob=new Blob(inputChunks,{type:inputChunks[0]?.type||'audio/webm'});const url=URL.createObjectURL(blob);const a=new Audio(url);a.onloadedmetadata=()=>{recordingBuffers[recordingSlot]=url;$('#inputPlay').disabled=false;$('#inputLoop').disabled=false;$('#inputRecord').setAttribute('aria-pressed','false');status(`Recording ${recordingSlot} saved.`);stream.getTracks().forEach(t=>t.stop());};};inputRecorder.start();$('#inputRecord').setAttribute('aria-pressed','true');status(`Recording microphone to slot ${recordingSlot}; it stops after five seconds.`);inputStopTimer=setTimeout(()=>inputRecorder.state==='recording'&&inputRecorder.stop(),5000);}catch{status('Microphone access was not available.');}}
  function playRecording(loop=false){const url=recordingBuffers[recordingSlot];if(!url)return;initAudio();if(recordingSources[recordingSlot]){recordingSources[recordingSlot].audio.pause();recordingSources[recordingSlot].source.disconnect();delete recordingSources[recordingSlot];$('#inputLoop').setAttribute('aria-pressed','false');return;}const audio=new Audio(url);audio.loop=loop;const source=ctx.createMediaElementSource(audio);source.connect($('#inputLink').getAttribute('aria-pressed')==='true'?fx.input:master);audio.onended=()=>{source.disconnect();delete recordingSources[recordingSlot];};recordingSources[recordingSlot]={audio,source};audio.play();$('#inputLoop').setAttribute('aria-pressed',String(loop));status(`Recording ${recordingSlot} ${loop?'looping':'playing once'}.`);}
  function reset(){Object.keys(LANE_INFO).forEach(stopLane);Object.values(recordingSources).forEach(x=>x.audio.pause());recordingSources={};linked.clear();document.querySelectorAll('.link,#inputLink').forEach(x=>x.setAttribute('aria-pressed','false'));setBPM(100);$('#effect').value='flanger';$('#fxX').value=$('#fxY').value=50;$('#hold').checked=false;status('Desk reset.');}
  let taps=[]; $('#tap').onclick=()=>{const now=performance.now();taps=[...taps,now].filter(t=>now-t<2400);if(taps.length>1)setBPM(Math.round(60000/((now-taps[0])/(taps.length-1))));status(`Tap tempo: ${bpm} BPM.`)};
  ['bpmDown','bpmUp'].forEach(id=>{const d=id==='bpmDown'?-1:1,b=$('#'+id);b.onclick=()=>setBPM(bpm+d);b.onpointerdown=()=>b._hold=setTimeout(()=>setBPM(100),700);b.onpointerup=b.onpointerleave=()=>clearTimeout(b._hold);});
  $('#masterVolume').oninput=e=>{initAudio();master.gain.value=e.target.value/100;$('#volumeOut').textContent=e.target.value+'%'}; $('#effect').onchange=updateFX;$('#fxX').oninput=updateFX;$('#fxY').oninput=updateFX;$('#pack').onchange=()=>{reset();loadPackRecordings();status(`${pack.value} loaded, including its two factory recordings.`)};$('#slot').onchange=e=>{recordingSlot=e.target.value;$('#inputPlay').disabled=!recordingBuffers[recordingSlot];$('#inputLoop').disabled=!recordingBuffers[recordingSlot];status(`Recording slot ${recordingSlot} selected.`)};$('#inputRecord').onclick=recordInput;$('#inputPlay').onclick=()=>playRecording(false);$('#inputLoop').onclick=()=>playRecording(true);$('#inputLink').onclick=e=>{const on=e.currentTarget.getAttribute('aria-pressed')!=='true';e.currentTarget.setAttribute('aria-pressed',String(on));status(`Recording ${on?'linked to':'unlinked from'} effects.`)};$('#songRecord').onclick=recordSong;$('#songPlay').onclick=toggleSongPlayback;$('#exportSong').onclick=()=>{const a=document.createElement('a');a.href=songUrl;a.download='UCreate-song.webm';a.click();status('Song export started.');};$('#reset').onclick=reset;
  addPads(); wireLinks(); loadPackRecordings();
})();
